### PR TITLE
Rory'ify everything.

### LINKED ISSUE #2: Not enough rory!
Add more rory pics

### PR DESCRIPTION
**Pull request by 7man7LMYT**
Closes #2 
Fixes #2 
Resolves #2

### CODE REVIEW

**Comment by 7man7LMYT** [comment]
Don't merge this yet pls.

**Comment by Chew** [comment]
what's left to do here

**Comment by 7man7LMYT** [comment]
We need to add more rory.

**Comment by Heath123** [comment]
We need to add more rory.

**Comment by Chew** [comment]
Everything is already rory!

**Comment by 7man7LMYT** [comment]
> Everything is already rory!

no it's missing 2 things!1

**Comment by 7man7LMYT** [comment]
okay so #9 needs to be merged before we merge this

**Comment by Chew** [comment]
Good now ?

**Comment by 7man7LMYT** [comment]
I'd say so, shall we?

**Comment by 7man7LMYT** [comment]
👍

**Pull request merged**
